### ISSUE TITLE
Questions and feedback

### ISSUE THREAD

**Issue by geeewizzz** [karloygard/hassio-addons#3]
I'm a bit of a noob when it comes to HA though, but let me try.

1. Seems like all my heating actuaturs come up as "light.xcomfort_deviceid..." , probably should be named differently.
2. It would be nice to easily add "climate" devices in home assistant, but I assume that it's difficult to match up automatically when installing the add-on because there is no way to know which sensor belongs to which heating actuator?
3. I tried adding one manually in the configuration:

```
 climate:
   - platform: generic_thermostat
     name: Liten gang
     heater: light.xcomfort_5733608_1_etg_liten_gang_vk
     target_sensor: sensor.xcomfort_5881353_1_etg_liten_gang_temp_kanal_b
```
Seems to be working, other than the fact if I turn up the wanted temp to a temp above the actual temp right now it doesn't start heating (which I hoped it would). 

<img width="474" alt="Screenshot 2020-04-13 at 20 23 48" src="https://user-images.githubusercontent.com/4536023/79147887-f7a3f180-7dc4-11ea-9de3-c5a247a1c780.png">
